### ISSUE TITLE
problem with ё

### ISSUE THREAD

**Issue by tamara11solo** [suralmasha/RuTranscript#1]
Hi, 
thanks for sharing this great library. It's very useful and I'm impressed by how many phonetic processes are taken into account. 

I'd like to report an issue to help the tool development: I've tried to transcribe some Russian sentences and discovered that words with letter ё are not dealt with correctly.

This is a test 'sentence': 
ёлка для её ёжика пёрышка подвёл конёк нёбо мёд. 
Here's the transcription I get:
ʝ ɪ l k ʌ dʲ lʲ æ j ɪ jᶣ ɵ j ɪ ʒ k ʌ pʲ j ɪ r ɨ ʂ k ʌ p ə d vʲ j ɪ l k ə nʲ ɪ k nʲ ɪ b æ. mʲ j ɪ d

another 'sentence'
елка для ежика перышка подвел конек небо мед
transcription:
ʝ ɪ l k ʌ dʲ lʲ æ j ɪ ʒ i k ʌ pʲ j ɪ r ɨ ʂ k ʌ p ə d vʲ j ɪ l k ə nʲ ɪ k nʲ ɪ b æ. mʲ j ɪ d

Thanks for your attention

**Comment by suralmasha** [comment]
Hi!
Thank you for your comment! I don't always notice my mistakes myself.
I've corrected the conversion of "e" to "ё", several transcription rules (for example, removed the assimilative softening of consonants before the soft "л" - для, глина, тлеть).

**Comment by tamara11solo** [comment]
Great! Huge thanks! <3
