### ISSUE TITLE
problem with "острого"

### ISSUE THREAD

**Issue by proger-coder** [suralmasha/RuTranscript#2]
Получаю ошибку при обработке слова "острого".
```python
from ru_transcript import RuTranscript
def getPhonemes(word):
    instance = RuTranscript(word)
    instance.transcribe()
    return instance.get_phonemes()

getPhonemes("острого") // выдаёт ошибку "substring not found"
``` 

при этом, нормально отрабатываются слова:
острог  -  ['o', 's', 't', 'r', 'o', 'k']
острго - ['o', 's', 't', 'r', 'ɡ', 'o']
острога - ['o', 's', 't', 'r', 'o', 'ɡ', 'a']
острогоо - ['o', 's', 't', 'r', 'o', 'ɡ', 'o', 'o']

**Comment by suralmasha** [comment]
Добрый день. Спасибо за обращение. Ошибка возникала из-за проблем с постановкой ударения. Она исправлена - f255775ff9f3a76d4896d54edfa4903183dbe172
