### ISSUE TITLE
Endless loop issue

### ISSUE THREAD

**Issue by tamara11solo** [suralmasha/RuTranscript#3]
Hi! 

I guess, a hyphen in words causes the Endless loop issue (raised in ru_transcript.py, line 130).
I've encountered that when getting allophones for the following sentences so far (all from RUSLAN Dataset):

1) Моя жена говорит, если бы ты оделся как следует… Между прочим, его жена звонит как‑то раз… Стоп!
2) С каким‑то идиотским простодушием он добавил Человек двадцать претендовало на место.
3) За пятьдесят лет спортсмены отвоевали немало призов и дипломов, а в одна тысяча девятьсот шестьдесят девятом году мастер‑наездник Антон Дукальский на жеребце Тальник выиграл Большой всесоюзный приз.

here's the error I get:
  File "/ru_transcript/ru_transcript.py", line 300, in transcribe
    self._lpt_4(section_num)
  File "/ru_transcript/ru_transcript.py", line 265, in _lpt_4
    joined_phonemes = self._join_phonemes(self._transliterated_tokens[section_num], limit=10000)
  File "/ru_transcript/ru_transcript.py", line 130, in _join_phonemes
    raise IndexError('Endless loop')
IndexError: Endless loop

I fixed the problem by replacing all hyphens with a space before transcribing but that's probably not the best solution))

**Comment by suralmasha** [comment]
Good afternoon! Thank you for contacting us! The error occurred because the hyphen in your examples and the hyphen in my dictionary did not match. I fixed this bug - 1302a88c9c982b6814eb54c2031fd11cef948871
